name: "Make prerelease"
description: "Makes prereleases on git push to npm"
author: "Esa-Matti Suuronen"
inputs:
    NPM_TOKEN:
        description: "npm publish token"
        required: true
    milliseconds:
        description: "ms"
        default: 100
runs:
    using: "node10"
    main: "lib/main.js"
